### PR TITLE
Update Apollo Client to V3

### PR DESCRIPTION
**Pull request by deanpienaar**

### CODE REVIEW

**Comment by dnacenta** [comment]
hey @mgtitimoli @tlvenn @bruce ! This would be very useful to us since we are using Apollo v.3 in our project. If you guys could take a look at it, it would be great 👍

**Review by BowenLi0214 — APPROVED** [review]

**Comment by dherault** [comment]
I really needed this as part of my job so I published this PR's work under:
`pluralsh-absinthe-socket-apollo-link`

Run `npm i --save pluralsh-absinthe-socket-apollo-link` and replace your imports accordingly.

Hope that helps.

**Comment by kyleboe** [comment]
Any timeline on merging this? (or something like it)

**Comment by kyleboe** [comment]
CC: @bruce, @mgtitimoli, @tlvenn, or someone with write access to the repo

**Comment by DavidSpek** [comment]
I've setup a new repo (from the one mentioned above by dherault) that has Nx and Semantic Release setup and includes this PR. It can be found at https://github.com/pluralsh/absinthe-socket and release to `@pluralsh/socket`, `@pluralsh/socket-apollo-link`, `@pluralsh/socket-graphiql` and `@pluralsh/socket-relay`.

**Pull request closed without merging**
